mkdir -p build
cd build
cmake .. ${CMAKE_ARGS} -DSIRIUS_USE_MKL=OFF -DSIRIUS_USE_SCALAPACK=ON -DSIRIUS_USE_OPENMP=ON -DSIRIUS_CREATE_PYTHON_MODULE=OFF -DSIRIUS_CREATE_FORTRAN_BINDINGS=ON -DSIRIUS_USE_MEMORY_POOL=OFF
make -j${CPU_COUNT} install
